server:
  port: 7070
  servlet:
    context-path: /SDEmpApp


spring:
  flyway:
    baseline-on-migrate: true
    locations: classpath:flyway/migrations
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/SDEmpApp
    username: postgres
    password: postgresql
    hikari:
      idle-timeout: 10000
      connectionTimeout: 20000
      minimumIdle: 10
      maximumPoolSize: 20

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    #    root: DEBUG
    #    pl.zajavka.api.controller: DEBUG
    org:
      springframework:
        security: DEBUG
