DROP TABLE IF EXISTS company CASCADE;
DROP TABLE IF EXISTS candidate CASCADE;
DROP TABLE IF EXISTS job_advertisement CASCADE;
DROP TABLE IF EXISTS localization CASCADE;
DROP TABLE IF EXISTS skill CASCADE;
