DROP TABLE IF EXISTS company CASCADE;
DROP TABLE IF EXISTS job_seeker CASCADE;
DROP TABLE IF EXISTS job_advertisement CASCADE;
DROP TABLE IF EXISTS localization CASCADE;
DROP TABLE IF EXISTS sdempapp_user CASCADE;
DROP TABLE IF EXISTS sdempapp_role CASCADE;
DROP TABLE IF EXISTS user_role CASCADE;