INSERT INTO localization (province_name, city_name)
values
('Dolnośląskie', 'Bardo'),
('Dolnośląskie', 'Bielawa'),
('Dolnośląskie', 'Bierutów'),
('Dolnośląskie', 'Bogatynia'),
('Dolnośląskie', 'Boguszów-Gorce'),
('Dolnośląskie', 'Bolesławiec'),
('Dolnośląskie', 'Bolków'),
('Dolnośląskie', 'Brzeg Dolny'),
('Dolnośląskie', 'Bystrzyca Kłodzka'),
('Dolnośląskie', 'Chocianów'),
('Dolnośląskie', 'Chojnów'),
('Dolnośląskie', 'Duszniki-Zdrój'),
('Dolnośląskie', 'Dzierżoniów'),
('Dolnośląskie', 'Głogów'),
('Dolnośląskie', 'Głuszyca'),
('Dolnośląskie', 'Góra'),
('Dolnośląskie', 'Gryfów Śląski'),
('Dolnośląskie', 'Jawor'),
('Dolnośląskie', 'Jaworzyna Śląska'),
('Dolnośląskie', 'Jedlina-Zdrój'),
('Dolnośląskie', 'Jelcz-Laskowice'),
('Dolnośląskie', 'Jelenia Góra'),
('Dolnośląskie', 'Kamieniec Ząbkowicki'),
('Dolnośląskie', 'Kamienna Góra'),
('Dolnośląskie', 'Karpacz'),
('Dolnośląskie', 'Kąty Wrocławskie'),
('Dolnośląskie', 'Kłodzko'),
('Dolnośląskie', 'Kowary'),
('Dolnośląskie', 'Kudowa-Zdrój'),
('Dolnośląskie', 'Lądek-Zdrój'),
('Dolnośląskie', 'Legnica'),
('Dolnośląskie', 'Leśna'),
('Dolnośląskie', 'Lubań'),
('Dolnośląskie', 'Lubawka'),
('Dolnośląskie', 'Lubin'),
('Dolnośląskie', 'Lubomierz'),
('Dolnośląskie', 'Lwówek Śląski'),
('Dolnośląskie', 'Mieroszów'),
('Dolnośląskie', 'Międzybórz'),
('Dolnośląskie', 'Międzylesie'),
('Dolnośląskie', 'Miękinia'),
('Dolnośląskie', 'Milicz'),
('Dolnośląskie', 'Mirsk'),
('Dolnośląskie', 'Niemcza'),
('Dolnośląskie', 'Nowa Ruda'),
('Dolnośląskie', 'Nowogrodziec'),
('Dolnośląskie', 'Oborniki Śląskie'),
('Dolnośląskie', 'Oleśnica'),
('Dolnośląskie', 'Olszyna'),
('Dolnośląskie', 'Oława'),
('Dolnośląskie', 'Piechowice'),
('Dolnośląskie', 'Pieńsk'),
('Dolnośląskie', 'Pieszyce'),
('Dolnośląskie', 'Piława Górna'),
('Dolnośląskie', 'Polanica-Zdrój'),
('Dolnośląskie', 'Polkowice'),
('Dolnośląskie', 'Prochowice'),
('Dolnośląskie', 'Prusice'),
('Dolnośląskie', 'Przemków'),
('Dolnośląskie', 'Radków'),
('Dolnośląskie', 'Siechnice'),
('Dolnośląskie', 'Sobótka'),
('Dolnośląskie', 'Stronie Śląskie'),
('Dolnośląskie', 'Strzegom'),
('Dolnośląskie', 'Strzelin'),
('Dolnośląskie', 'Syców'),
('Dolnośląskie', 'Szczawno-Zdrój'),
('Dolnośląskie', 'Szczytna'),
('Dolnośląskie', 'Szklarska Poręba'),
('Dolnośląskie', 'Ścinawa'),
('Dolnośląskie', 'Środa Śląska'),
('Dolnośląskie', 'Świdnica'),
('Dolnośląskie', 'Świebodzice'),
('Dolnośląskie', 'Świeradów-Zdrój'),
('Dolnośląskie', 'Świerzawa'),
('Dolnośląskie', 'Trzebnica'),
('Dolnośląskie', 'Twardogóra'),
('Dolnośląskie', 'Wałbrzych'),
('Dolnośląskie', 'Wąsosz'),
('Dolnośląskie', 'Węgliniec'),
('Dolnośląskie', 'Wiązów'),
('Dolnośląskie', 'Wleń'),
('Dolnośląskie', 'Wojcieszów'),
('Dolnośląskie', 'Wołów'),
('Dolnośląskie', 'Wrocław'),
('Dolnośląskie', 'Zawidów'),
('Dolnośląskie', 'Ząbkowice Śląskie'),
('Dolnośląskie', 'Zgorzelec'),
('Dolnośląskie', 'Ziębice'),
('Dolnośląskie', 'Złotoryja'),
('Dolnośląskie', 'Złoty Stok'),
('Dolnośląskie', 'Żarów'),
('Dolnośląskie', 'Żmigród'),
('Kujawsko-pomorskie', 'Aleksandrów Kujawski'),
('Kujawsko-pomorskie', 'Barcin'),
('Kujawsko-pomorskie', 'Brodnica'),
('Kujawsko-pomorskie', 'Brześć Kujawski'),
('Kujawsko-pomorskie', 'Bydgoszcz'),
('Kujawsko-pomorskie', 'Chełmno'),
('Kujawsko-pomorskie', 'Chełmża'),
('Kujawsko-pomorskie', 'Chodecz'),
('Kujawsko-pomorskie', 'Ciechocinek'),
('Kujawsko-pomorskie', 'Dobrzyń nad Wisłą'),
('Kujawsko-pomorskie', 'Gniewkowo'),
('Kujawsko-pomorskie', 'Golub-Dobrzyń'),
('Kujawsko-pomorskie', 'Górzno'),
('Kujawsko-pomorskie', 'Grudziądz'),
('Kujawsko-pomorskie', 'Inowrocław'),
('Kujawsko-pomorskie', 'Izbica Kujawska'),
('Kujawsko-pomorskie', 'Jabłonowo Pomorskie'),
('Kujawsko-pomorskie', 'Janikowo'),
('Kujawsko-pomorskie', 'Janowiec Wielkopolski'),
('Kujawsko-pomorskie', 'Kamień Krajeński'),
('Kujawsko-pomorskie', 'Kcynia'),
('Kujawsko-pomorskie', 'Koronowo'),
('Kujawsko-pomorskie', 'Kowal'),
('Kujawsko-pomorskie', 'Kowalewo Pomorskie'),
('Kujawsko-pomorskie', 'Kruszwica'),
('Kujawsko-pomorskie', 'Lipno'),
('Kujawsko-pomorskie', 'Lubień Kujawski'),
('Kujawsko-pomorskie', 'Lubraniec'),
('Kujawsko-pomorskie', 'Łabiszyn'),
('Kujawsko-pomorskie', 'Łasin'),
('Kujawsko-pomorskie', 'Mogilno'),
('Kujawsko-pomorskie', 'Mrocza'),
('Kujawsko-pomorskie', 'Nakło nad Notecią'),
('Kujawsko-pomorskie', 'Nieszawa'),
('Kujawsko-pomorskie', 'Nowe'),
('Kujawsko-pomorskie', 'Pakość'),
('Kujawsko-pomorskie', 'Piotrków Kujawski'),
('Kujawsko-pomorskie', 'Pruszcz'),
('Kujawsko-pomorskie', 'Radziejów'),
('Kujawsko-pomorskie', 'Radzyń Chełmiński'),
('Kujawsko-pomorskie', 'Rypin'),
('Kujawsko-pomorskie', 'Sępólno Krajeńskie'),
('Kujawsko-pomorskie', 'Skępe'),
('Kujawsko-pomorskie', 'Solec Kujawski'),
('Kujawsko-pomorskie', 'Strzelno'),
('Kujawsko-pomorskie', 'Szubin'),
('Kujawsko-pomorskie', 'Świecie'),
('Kujawsko-pomorskie', 'Toruń'),
('Kujawsko-pomorskie', 'Tuchola'),
('Kujawsko-pomorskie', 'Wąbrzeźno'),
('Kujawsko-pomorskie', 'Więcbork'),
('Kujawsko-pomorskie', 'Włocławek'),
('Kujawsko-pomorskie', 'Żnin'),
('Lubelskie', 'Annopol'),
('Lubelskie', 'Bełżyce'),
('Lubelskie', 'Biała Podlaska'),
('Lubelskie', 'Biłgoraj'),
('Lubelskie', 'Bychawa'),
('Lubelskie', 'Chełm'),
('Lubelskie', 'Dęblin'),
('Lubelskie', 'Frampol'),
('Lubelskie', 'Goraj'),
('Lubelskie', 'Hrubieszów'),
('Lubelskie', 'Izbica'),
('Lubelskie', 'Janów Lubelski'),
('Lubelskie', 'Józefów'),
('Lubelskie', 'Józefów nad Wisłą'),
('Lubelskie', 'Kamionka'),
('Lubelskie', 'Kazimierz Dolny'),
('Lubelskie', 'Kock'),
('Lubelskie', 'Krasnobród'),
('Lubelskie', 'Krasnystaw'),
('Lubelskie', 'Kraśnik'),
('Lubelskie', 'Lubartów'),
('Lubelskie', 'Lublin'),
('Lubelskie', 'Lubycza Królewska'),
('Lubelskie', 'Łaszczów'),
('Lubelskie', 'Łęczna'),
('Lubelskie', 'Łuków'),
('Lubelskie', 'Międzyrzec Podlaski'),
('Lubelskie', 'Modliborzyce'),
('Lubelskie', 'Nałęczów'),
('Lubelskie', 'Opole Lubelskie'),
('Lubelskie', 'Ostrów Lubelski'),
('Lubelskie', 'Parczew'),
('Lubelskie', 'Piaski'),
('Lubelskie', 'Poniatowa'),
('Lubelskie', 'Puławy'),
('Lubelskie', 'Radzyń Podlaski'),
('Lubelskie', 'Rejowiec'),
('Lubelskie', 'Rejowiec Fabryczny'),
('Lubelskie', 'Ryki'),
('Lubelskie', 'Siedliszcze'),
('Lubelskie', 'Stoczek Łukowski'),
('Lubelskie', 'Szczebrzeszyn'),
('Lubelskie', 'Świdnik'),
('Lubelskie', 'Tarnogród'),
('Lubelskie', 'Terespol'),
('Lubelskie', 'Tomaszów Lubelski'),
('Lubelskie', 'Tyszowce'),
('Lubelskie', 'Urzędów'),
('Lubelskie', 'Włodawa'),
('Lubelskie', 'Zamość'),
('Lubelskie', 'Zwierzyniec'),
('Lubuskie', 'Babimost'),
('Lubuskie', 'Bytom Odrzański'),
('Lubuskie', 'Cybinka'),
('Lubuskie', 'Czerwieńsk'),
('Lubuskie', 'Dobiegniew'),
('Lubuskie', 'Drezdenko'),
('Lubuskie', 'Gorzów Wielkopolski'),
('Lubuskie', 'Gozdnica'),
('Lubuskie', 'Gubin'),
('Lubuskie', 'Iłowa'),
('Lubuskie', 'Jasień'),
('Lubuskie', 'Kargowa'),
('Lubuskie', 'Kostrzyn nad Odrą'),
('Lubuskie', 'Kożuchów'),
('Lubuskie', 'Krosno Odrzańskie'),
('Lubuskie', 'Lubniewice'),
('Lubuskie', 'Lubsko'),
('Lubuskie', 'Łęknica'),
('Lubuskie', 'Małomice'),
('Lubuskie', 'Międzyrzecz'),
('Lubuskie', 'Nowa Sól'),
('Lubuskie', 'Nowe Miasteczko'),
('Lubuskie', 'Nowogród Bobrzański'),
('Lubuskie', 'Ośno Lubuskie'),
('Lubuskie', 'Otyń'),
('Lubuskie', 'Rzepin'),
('Lubuskie', 'Skwierzyna'),
('Lubuskie', 'Sława'),
('Lubuskie', 'Słubice'),
('Lubuskie', 'Strzelce Krajeńskie'),
('Lubuskie', 'Sulechów'),
('Lubuskie', 'Sulęcin'),
('Lubuskie', 'Szlichtyngowa'),
('Lubuskie', 'Szprotawa'),
('Lubuskie', 'Świebodzin'),
('Lubuskie', 'Torzym'),
('Lubuskie', 'Trzciel'),
('Lubuskie', 'Witnica'),
('Lubuskie', 'Wschowa'),
('Lubuskie', 'Zbąszynek'),
('Lubuskie', 'Zielona Góra'),
('Lubuskie', 'Żagań'),
('Lubuskie', 'Żary'),
('Łódzkie', 'Aleksandrów Łódzki'),
('Łódzkie', 'Bełchatów'),
('Łódzkie', 'Biała Rawska'),
('Łódzkie', 'Błaszki'),
('Łódzkie', 'Bolimów'),
('Łódzkie', 'Brzeziny'),
('Łódzkie', 'Dąbrowice'),
('Łódzkie', 'Drzewica'),
('Łódzkie', 'Działoszyn'),
('Łódzkie', 'Głowno'),
('Łódzkie', 'Jeżów'),
('Łódzkie', 'Kamieńsk'),
('Łódzkie', 'Koluszki'),
('Łódzkie', 'Konstantynów Łódzki'),
('Łódzkie', 'Krośniewice'),
('Łódzkie', 'Kutno'),
('Łódzkie', 'Lutomiersk'),
('Łódzkie', 'Lututów'),
('Łódzkie', 'Łask'),
('Łódzkie', 'Łęczyca'),
('Łódzkie', 'Łowicz'),
('Łódzkie', 'Łódź'),
('Łódzkie', 'Opoczno'),
('Łódzkie', 'Ozorków'),
('Łódzkie', 'Pabianice'),
('Łódzkie', 'Pajęczno'),
('Łódzkie', 'Piątek'),
('Łódzkie', 'Piotrków Trybunalski'),
('Łódzkie', 'Poddębice'),
('Łódzkie', 'Przedbórz'),
('Łódzkie', 'Radomsko'),
('Łódzkie', 'Rawa Mazowiecka'),
('Łódzkie', 'Rozprza'),
('Łódzkie', 'Rzgów'),
('Łódzkie', 'Sieradz'),
('Łódzkie', 'Skierniewice'),
('Łódzkie', 'Stryków'),
('Łódzkie', 'Sulejów'),
('Łódzkie', 'Szadek'),
('Łódzkie', 'Tomaszów Mazowiecki'),
('Łódzkie', 'Tuszyn'),
('Łódzkie', 'Ujazd'),
('Łódzkie', 'Uniejów'),
('Łódzkie', 'Warta'),
('Łódzkie', 'Wieluń'),
('Łódzkie', 'Wieruszów'),
('Łódzkie', 'Wolbórz'),
('Łódzkie', 'Zduńska Wola'),
('Łódzkie', 'Zelów'),
('Łódzkie', 'Zgierz'),
('Łódzkie', 'Złoczew'),
('Łódzkie', 'Żychlin'),
('Małopolskie', 'Alwernia'),
('Małopolskie', 'Andrychów'),
('Małopolskie', 'Biecz'),
('Małopolskie', 'Bobowa'),
('Małopolskie', 'Bochnia'),
('Małopolskie', 'Brzesko'),
('Małopolskie', 'Brzeszcze'),
('Małopolskie', 'Bukowno'),
('Małopolskie', 'Czarny Dunajec'),
('Małopolskie', 'Chełmek'),
('Małopolskie', 'Chrzanów'),
('Małopolskie', 'Ciężkowice'),
('Małopolskie', 'Czchów'),
('Małopolskie', 'Dąbrowa Tarnowska'),
('Małopolskie', 'Dobczyce'),
('Małopolskie', 'Gorlice'),
('Małopolskie', 'Grybów'),
('Małopolskie', 'Jordanów'),
('Małopolskie', 'Kalwaria Zebrzydowska'),
('Małopolskie', 'Kęty'),
('Małopolskie', 'Książ Wielki'),
('Małopolskie', 'Koszyce'),
('Małopolskie', 'Kraków'),
('Małopolskie', 'Krynica-Zdrój'),
('Małopolskie', 'Krzeszowice'),
('Małopolskie', 'Libiąż'),
('Małopolskie', 'Limanowa'),
('Małopolskie', 'Maków Podhalański'),
('Małopolskie', 'Miechów'),
('Małopolskie', 'Mszana Dolna'),
('Małopolskie', 'Muszyna'),
('Małopolskie', 'Myślenice'),
('Małopolskie', 'Niepołomice'),
('Małopolskie', 'Nowe Brzesko'),
('Małopolskie', 'Nowy Sącz'),
('Małopolskie', 'Nowy Targ'),
('Małopolskie', 'Nowy Wiśnicz'),
('Małopolskie', 'Olkusz'),
('Małopolskie', 'Oświęcim'),
('Małopolskie', 'Piwniczna-Zdrój'),
('Małopolskie', 'Proszowice'),
('Małopolskie', 'Rabka-Zdrój'),
('Małopolskie', 'Radłów'),
('Małopolskie', 'Ryglice'),
('Małopolskie', 'Skała'),
('Małopolskie', 'Skawina'),
('Małopolskie', 'Słomniki'),
('Małopolskie', 'Stary Sącz'),
('Małopolskie', 'Sucha Beskidzka'),
('Małopolskie', 'Sułkowice'),
('Małopolskie', 'Szczawnica'),
('Małopolskie', 'Szczucin'),
('Małopolskie', 'Świątniki Górne'),
('Małopolskie', 'Tarnów'),
('Małopolskie', 'Trzebinia'),
('Małopolskie', 'Tuchów'),
('Małopolskie', 'Wadowice'),
('Małopolskie', 'Wieliczka'),
('Małopolskie', 'Wojnicz'),
('Małopolskie', 'Wolbrom'),
('Małopolskie', 'Zakliczyn'),
('Małopolskie', 'Zakopane'),
('Małopolskie', 'Zator'),
('Małopolskie', 'Żabno'),
('Mazowieckie', 'Białobrzegi'),
('Mazowieckie', 'Bieżuń'),
('Mazowieckie', 'Błonie'),
('Mazowieckie', 'Bodzanów'),
('Mazowieckie', 'Brok'),
('Mazowieckie', 'Brwinów'),
('Mazowieckie', 'Cegłów'),
('Mazowieckie', 'Chorzele'),
('Mazowieckie', 'Ciechanów'),
('Mazowieckie', 'Czerwińsk nad Wisłą'),
('Mazowieckie', 'Drobin'),
('Mazowieckie', 'Garwolin'),
('Mazowieckie', 'Gąbin'),
('Mazowieckie', 'Glinojeck'),
('Mazowieckie', 'Gostynin'),
('Mazowieckie', 'Góra Kalwaria'),
('Mazowieckie', 'Grodzisk Mazowiecki'),
('Mazowieckie', 'Grójec'),
('Mazowieckie', 'Halinów'),
('Mazowieckie', 'Iłża'),
('Mazowieckie', 'Jadów'),
('Mazowieckie', 'Jastrząb'),
('Mazowieckie', 'Jedlnia-Letnisko'),
('Mazowieckie', 'Józefów'),
('Mazowieckie', 'Kałuszyn'),
('Mazowieckie', 'Karczew'),
('Mazowieckie', 'Kobyłka'),
('Mazowieckie', 'Konstancin-Jeziorna'),
('Mazowieckie', 'Kosów Lacki'),
('Mazowieckie', 'Kozienice'),
('Mazowieckie', 'Latowicz'),
('Mazowieckie', 'Legionowo'),
('Mazowieckie', 'Lipsko'),
('Mazowieckie', 'Lubowidz'),
('Mazowieckie', 'Łaskarzew'),
('Mazowieckie', 'Łochów'),
('Mazowieckie', 'Łomianki'),
('Mazowieckie', 'Łosice'),
('Mazowieckie', 'Maków Mazowiecki'),
('Mazowieckie', 'Marki'),
('Mazowieckie', 'Milanówek'),
('Mazowieckie', 'Mińsk Mazowiecki'),
('Mazowieckie', 'Mława'),
('Mazowieckie', 'Mogielnica'),
('Mazowieckie', 'Mordy'),
('Mazowieckie', 'Mrozy'),
('Mazowieckie', 'Mszczonów'),
('Mazowieckie', 'Myszyniec'),
('Mazowieckie', 'Nasielsk'),
('Mazowieckie', 'Nowe Miasto'),
('Mazowieckie', 'Nowe Miasto nad Pilicą'),
('Mazowieckie', 'Nowy Dwór Mazowiecki'),
('Mazowieckie', 'Ostrołęka'),
('Mazowieckie', 'Ostrów Mazowiecka'),
('Mazowieckie', 'Otwock'),
('Mazowieckie', 'Ożarów Mazowiecki'),
('Mazowieckie', 'Piaseczno'),
('Mazowieckie', 'Piastów'),
('Mazowieckie', 'Pilawa'),
('Mazowieckie', 'Pionki'),
('Mazowieckie', 'Płock'),
('Mazowieckie', 'Płońsk'),
('Mazowieckie', 'Podkowa Leśna'),
('Mazowieckie', 'Pruszków'),
('Mazowieckie', 'Przasnysz'),
('Mazowieckie', 'Przysucha'),
('Mazowieckie', 'Pułtusk'),
('Mazowieckie', 'Raciąż'),
('Mazowieckie', 'Radom'),
('Mazowieckie', 'Radzymin'),
('Mazowieckie', 'Różan'),
('Mazowieckie', 'Sanniki'),
('Mazowieckie', 'Serock'),
('Mazowieckie', 'Siedlce'),
('Mazowieckie', 'Sierpc'),
('Mazowieckie', 'Skaryszew'),
('Mazowieckie', 'Sochaczew'),
('Mazowieckie', 'Sochocin'),
('Mazowieckie', 'Sokołów Podlaski'),
('Mazowieckie', 'Solec nad Wisłą'),
('Mazowieckie', 'Sulejówek'),
('Mazowieckie', 'Szydłowiec'),
('Mazowieckie', 'Tarczyn'),
('Mazowieckie', 'Tłuszcz'),
('Mazowieckie', 'Warka'),
('Mazowieckie', 'Warszawa'),
('Mazowieckie', 'Węgrów'),
('Mazowieckie', 'Wiskitki'),
('Mazowieckie', 'Wołomin'),
('Mazowieckie', 'Wyszków'),
('Mazowieckie', 'Wyszogród'),
('Mazowieckie', 'Wyśmierzyce'),
('Mazowieckie', 'Zakroczym'),
('Mazowieckie', 'Ząbki'),
('Mazowieckie', 'Zielonka'),
('Mazowieckie', 'Zwoleń'),
('Mazowieckie', 'Żelechów'),
('Mazowieckie', 'Żuromin'),
('Mazowieckie', 'Żyrardów'),
('Opolskie', 'Baborów'),
('Opolskie', 'Biała'),
('Opolskie', 'Brzeg'),
('Opolskie', 'Byczyna'),
('Opolskie', 'Dobrodzień'),
('Opolskie', 'Głogówek'),
('Opolskie', 'Głubczyce'),
('Opolskie', 'Głuchołazy'),
('Opolskie', 'Gogolin'),
('Opolskie', 'Gorzów Śląski'),
('Opolskie', 'Grodków'),
('Opolskie', 'Kędzierzyn-Koźle'),
('Opolskie', 'Kietrz'),
('Opolskie', 'Kluczbork'),
('Opolskie', 'Kolonowskie'),
('Opolskie', 'Korfantów'),
('Opolskie', 'Krapkowice'),
('Opolskie', 'Leśnica'),
('Opolskie', 'Lewin Brzeski'),
('Opolskie', 'Namysłów'),
('Opolskie', 'Niemodlin'),
('Opolskie', 'Nysa'),
('Opolskie', 'Olesno'),
('Opolskie', 'Opole'),
('Opolskie', 'Otmuchów'),
('Opolskie', 'Ozimek'),
('Opolskie', 'Paczków'),
('Opolskie', 'Praszka'),
('Opolskie', 'Prószków'),
('Opolskie', 'Prudnik'),
('Opolskie', 'Strzelce Opolskie'),
('Opolskie', 'Tułowice'),
('Opolskie', 'Ujazd'),
('Opolskie', 'Wołczyn'),
('Opolskie', 'Zawadzkie'),
('Opolskie', 'Zdzieszowice'),
('Podkarpackie', 'Baranów Sandomierski'),
('Podkarpackie', 'Błażowa'),
('Podkarpackie', 'Boguchwała'),
('Podkarpackie', 'Brzostek'),
('Podkarpackie', 'Brzozów'),
('Podkarpackie', 'Cieszanów'),
('Podkarpackie', 'Dębica'),
('Podkarpackie', 'Dubiecko'),
('Podkarpackie', 'Dukla'),
('Podkarpackie', 'Dynów'),
('Podkarpackie', 'Głogów Małopolski'),
('Podkarpackie', 'Iwonicz-Zdrój'),
('Podkarpackie', 'Jarosław'),
('Podkarpackie', 'Jasło'),
('Podkarpackie', 'Jedlicze'),
('Podkarpackie', 'Kańczuga'),
('Podkarpackie', 'Kolbuszowa'),
('Podkarpackie', 'Kołaczyce'),
('Podkarpackie', 'Krosno'),
('Podkarpackie', 'Lesko'),
('Podkarpackie', 'Leżajsk'),
('Podkarpackie', 'Lubaczów'),
('Podkarpackie', 'Łańcut'),
('Podkarpackie', 'Mielec'),
('Podkarpackie', 'Narol'),
('Podkarpackie', 'Nisko'),
('Podkarpackie', 'Nowa Dęba'),
('Podkarpackie', 'Nowa Sarzyna'),
('Podkarpackie', 'Oleszyce'),
('Podkarpackie', 'Pilzno'),
('Podkarpackie', 'Pruchnik'),
('Podkarpackie', 'Przecław'),
('Podkarpackie', 'Przemyśl'),
('Podkarpackie', 'Przeworsk'),
('Podkarpackie', 'Radomyśl Wielki'),
('Podkarpackie', 'Radymno'),
('Podkarpackie', 'Ropczyce'),
('Podkarpackie', 'Rudnik nad Sanem'),
('Podkarpackie', 'Rymanów'),
('Podkarpackie', 'Rzeszów'),
('Podkarpackie', 'Sanok'),
('Podkarpackie', 'Sędziszów Małopolski'),
('Podkarpackie', 'Sieniawa'),
('Podkarpackie', 'Sokołów Małopolski'),
('Podkarpackie', 'Stalowa Wola'),
('Podkarpackie', 'Strzyżów'),
('Podkarpackie', 'Tarnobrzeg'),
('Podkarpackie', 'Tyczyn'),
('Podkarpackie', 'Ulanów'),
('Podkarpackie', 'Ustrzyki Dolne'),
('Podkarpackie', 'Zagórz'),
('Podkarpackie', 'Zaklików'),
('Podlaskie', 'Augustów'),
('Podlaskie', 'Białystok'),
('Podlaskie', 'Bielsk Podlaski'),
('Podlaskie', 'Brańsk'),
('Podlaskie', 'Choroszcz'),
('Podlaskie', 'Ciechanowiec'),
('Podlaskie', 'Czarna Białostocka'),
('Podlaskie', 'Czyżew'),
('Podlaskie', 'Dąbrowa Białostocka'),
('Podlaskie', 'Drohiczyn'),
('Podlaskie', 'Goniądz'),
('Podlaskie', 'Grajewo'),
('Podlaskie', 'Hajnówka'),
('Podlaskie', 'Jedwabne'),
('Podlaskie', 'Kleszczele'),
('Podlaskie', 'Knyszyn'),
('Podlaskie', 'Kolno'),
('Podlaskie', 'Krynki'),
('Podlaskie', 'Lipsk'),
('Podlaskie', 'Łapy'),
('Podlaskie', 'Łomża'),
('Podlaskie', 'Michałowo'),
('Podlaskie', 'Mońki'),
('Podlaskie', 'Nowogród'),
('Podlaskie', 'Rajgród'),
('Podlaskie', 'Sejny'),
('Podlaskie', 'Siemiatycze'),
('Podlaskie', 'Sokółka'),
('Podlaskie', 'Stawiski'),
('Podlaskie', 'Suchowola'),
('Podlaskie', 'Supraśl'),
('Podlaskie', 'Suraż'),
('Podlaskie', 'Suwałki'),
('Podlaskie', 'Szczuczyn'),
('Podlaskie', 'Szepietowo'),
('Podlaskie', 'Tykocin'),
('Podlaskie', 'Wasilków'),
('Podlaskie', 'Wysokie Mazowieckie'),
('Podlaskie', 'Zabłudów'),
('Podlaskie', 'Zambrów'),
('Pomorskie', 'Brusy'),
('Pomorskie', 'Bytów'),
('Pomorskie', 'Chojnice'),
('Pomorskie', 'Czarna Woda'),
('Pomorskie', 'Czarne'),
('Pomorskie', 'Czersk'),
('Pomorskie', 'Człuchów'),
('Pomorskie', 'Debrzno'),
('Pomorskie', 'Dzierzgoń'),
('Pomorskie', 'Gdańsk'),
('Pomorskie', 'Gdynia'),
('Pomorskie', 'Gniew'),
('Pomorskie', 'Hel'),
('Pomorskie', 'Jastarnia'),
('Pomorskie', 'Kartuzy'),
('Pomorskie', 'Kępice'),
('Pomorskie', 'Kościerzyna'),
('Pomorskie', 'Krynica Morska'),
('Pomorskie', 'Kwidzyn'),
('Pomorskie', 'Lębork'),
('Pomorskie', 'Łeba'),
('Pomorskie', 'Malbork'),
('Pomorskie', 'Miastko'),
('Pomorskie', 'Nowy Dwór Gdański'),
('Pomorskie', 'Nowy Staw'),
('Pomorskie', 'Pelplin'),
('Pomorskie', 'Prabuty'),
('Pomorskie', 'Pruszcz Gdański'),
('Pomorskie', 'Puck'),
('Pomorskie', 'Reda'),
('Pomorskie', 'Rumia'),
('Pomorskie', 'Skarszewy'),
('Pomorskie', 'Skórcz'),
('Pomorskie', 'Słupsk'),
('Pomorskie', 'Sopot'),
('Pomorskie', 'Starogard Gdański'),
('Pomorskie', 'Sztum'),
('Pomorskie', 'Tczew'),
('Pomorskie', 'Ustka'),
('Pomorskie', 'Wejherowo'),
('Pomorskie', 'Władysławowo'),
('Pomorskie', 'Żukowo'),
('Śląskie', 'Będzin'),
('Śląskie', 'Bielsko-Biała'),
('Śląskie', 'Bieruń'),
('Śląskie', 'Blachownia'),
('Śląskie', 'Bytom'),
('Śląskie', 'Chorzów'),
('Śląskie', 'Cieszyn'),
('Śląskie', 'Czechowice-Dziedzice'),
('Śląskie', 'Czeladź'),
('Śląskie', 'Czerwionka-Leszczyny'),
('Śląskie', 'Częstochowa'),
('Śląskie', 'Dąbrowa Górnicza'),
('Śląskie', 'Gliwice'),
('Śląskie', 'Imielin'),
('Śląskie', 'Jastrzębie-Zdrój'),
('Śląskie', 'Jaworzno'),
('Śląskie', 'Kalety'),
('Śląskie', 'Katowice'),
('Śląskie', 'Kłobuck'),
('Śląskie', 'Knurów'),
('Śląskie', 'Koniecpol'),
('Śląskie', 'Koziegłowy'),
('Śląskie', 'Krzanowice'),
('Śląskie', 'Krzepice'),
('Śląskie', 'Kuźnia Raciborska'),
('Śląskie', 'Lędziny'),
('Śląskie', 'Lubliniec'),
('Śląskie', 'Łaziska Górne'),
('Śląskie', 'Łazy'),
('Śląskie', 'Miasteczko Śląskie'),
('Śląskie', 'Mikołów'),
('Śląskie', 'Mysłowice'),
('Śląskie', 'Myszków'),
('Śląskie', 'Ogrodzieniec'),
('Śląskie', 'Olsztyn'),
('Śląskie', 'Orzesze'),
('Śląskie', 'Piekary Śląskie'),
('Śląskie', 'Pilica'),
('Śląskie', 'Poręba'),
('Śląskie', 'Pszczyna'),
('Śląskie', 'Pszów'),
('Śląskie', 'Pyskowice'),
('Śląskie', 'Racibórz'),
('Śląskie', 'Radlin'),
('Śląskie', 'Radzionków'),
('Śląskie', 'Ruda Śląska'),
('Śląskie', 'Rybnik'),
('Śląskie', 'Rydułtowy'),
('Śląskie', 'Siemianowice Śląskie'),
('Śląskie', 'Siewierz'),
('Śląskie', 'Skoczów'),
('Śląskie', 'Sławków'),
('Śląskie', 'Sosnowiec'),
('Śląskie', 'Sośnicowice'),
('Śląskie', 'Strumień'),
('Śląskie', 'Szczekociny'),
('Śląskie', 'Szczyrk'),
('Śląskie', 'Świętochłowice'),
('Śląskie', 'Tarnowskie Góry'),
('Śląskie', 'Toszek'),
('Śląskie', 'Tychy'),
('Śląskie', 'Ustroń'),
('Śląskie', 'Wilamowice'),
('Śląskie', 'Wisła'),
('Śląskie', 'Włodowice'),
('Śląskie', 'Wodzisław Śląski'),
('Śląskie', 'Wojkowice'),
('Śląskie', 'Woźniki'),
('Śląskie', 'Zabrze'),
('Śląskie', 'Zawiercie'),
('Śląskie', 'Żarki'),
('Śląskie', 'Żory'),
('Śląskie', 'Żywiec'),
('Świętokrzyskie', 'Bodzentyn'),
('Świętokrzyskie', 'Busko-Zdrój'),
('Świętokrzyskie', 'Chęciny'),
('Świętokrzyskie', 'Chmielnik'),
('Świętokrzyskie', 'Ćmielów'),
('Świętokrzyskie', 'Daleszyce'),
('Świętokrzyskie', 'Działoszyce'),
('Świętokrzyskie', 'Iwaniska'),
('Świętokrzyskie', 'Jędrzejów'),
('Świętokrzyskie', 'Kazimierza Wielka'),
('Świętokrzyskie', 'Kielce'),
('Świętokrzyskie', 'Klimontów'),
('Świętokrzyskie', 'Końskie'),
('Świętokrzyskie', 'Koprzywnica'),
('Świętokrzyskie', 'Kunów'),
('Świętokrzyskie', 'Łagów'),
('Świętokrzyskie', 'Małogoszcz'),
('Świętokrzyskie', 'Morawica'),
('Świętokrzyskie', 'Nowa Słupia'),
('Świętokrzyskie', 'Nowy Korczyn'),
('Świętokrzyskie', 'Oleśnica'),
('Świętokrzyskie', 'Opatowiec'),
('Świętokrzyskie', 'Opatów'),
('Świętokrzyskie', 'Osiek'),
('Świętokrzyskie', 'Ostrowiec Świętokrzyski'),
('Świętokrzyskie', 'Ożarów'),
('Świętokrzyskie', 'Pacanów'),
('Świętokrzyskie', 'Piekoszów'),
('Świętokrzyskie', 'Pierzchnica'),
('Świętokrzyskie', 'Pińczów'),
('Świętokrzyskie', 'Połaniec'),
('Świętokrzyskie', 'Radoszyce'),
('Świętokrzyskie', 'Sandomierz'),
('Świętokrzyskie', 'Sędziszów'),
('Świętokrzyskie', 'Skalbmierz'),
('Świętokrzyskie', 'Skarżysko-Kamienna'),
('Świętokrzyskie', 'Starachowice'),
('Świętokrzyskie', 'Staszów'),
('Świętokrzyskie', 'Stąporków'),
('Świętokrzyskie', 'Stopnica'),
('Świętokrzyskie', 'Suchedniów'),
('Świętokrzyskie', 'Szydłów'),
('Świętokrzyskie', 'Wąchock'),
('Świętokrzyskie', 'Wiślica'),
('Świętokrzyskie', 'Włoszczowa'),
('Świętokrzyskie', 'Wodzisław'),
('Świętokrzyskie', 'Zawichost'),
('Warmińsko-mazurskie', 'Barczewo'),
('Warmińsko-mazurskie', 'Bartoszyce'),
('Warmińsko-mazurskie', 'Biała Piska'),
('Warmińsko-mazurskie', 'Biskupiec'),
('Warmińsko-mazurskie', 'Bisztynek'),
('Warmińsko-mazurskie', 'Braniewo'),
('Warmińsko-mazurskie', 'Dobre Miasto'),
('Warmińsko-mazurskie', 'Działdowo'),
('Warmińsko-mazurskie', 'Elbląg'),
('Warmińsko-mazurskie', 'Ełk'),
('Warmińsko-mazurskie', 'Frombork'),
('Warmińsko-mazurskie', 'Giżycko'),
('Warmińsko-mazurskie', 'Gołdap'),
('Warmińsko-mazurskie', 'Górowo Iławeckie'),
('Warmińsko-mazurskie', 'Iława'),
('Warmińsko-mazurskie', 'Jeziorany'),
('Warmińsko-mazurskie', 'Kętrzyn'),
('Warmińsko-mazurskie', 'Kisielice'),
('Warmińsko-mazurskie', 'Korsze'),
('Warmińsko-mazurskie', 'Lidzbark'),
('Warmińsko-mazurskie', 'Lidzbark Warmiński'),
('Warmińsko-mazurskie', 'Lubawa'),
('Warmińsko-mazurskie', 'Mikołajki'),
('Warmińsko-mazurskie', 'Miłakowo'),
('Warmińsko-mazurskie', 'Miłomłyn'),
('Warmińsko-mazurskie', 'Młynary'),
('Warmińsko-mazurskie', 'Morąg'),
('Warmińsko-mazurskie', 'Mrągowo'),
('Warmińsko-mazurskie', 'Nidzica'),
('Warmińsko-mazurskie', 'Nowe Miasto Lubawskie'),
('Warmińsko-mazurskie', 'Olecko'),
('Warmińsko-mazurskie', 'Olsztyn'),
('Warmińsko-mazurskie', 'Olsztynek'),
('Warmińsko-mazurskie', 'Orneta'),
('Warmińsko-mazurskie', 'Orzysz'),
('Warmińsko-mazurskie', 'Ostróda'),
('Warmińsko-mazurskie', 'Pasłęk'),
('Warmińsko-mazurskie', 'Pasym'),
('Warmińsko-mazurskie', 'Pieniężno'),
('Warmińsko-mazurskie', 'Pisz'),
('Warmińsko-mazurskie', 'Reszel'),
('Warmińsko-mazurskie', 'Ruciane-Nida'),
('Warmińsko-mazurskie', 'Ryn'),
('Warmińsko-mazurskie', 'Sępopol'),
('Warmińsko-mazurskie', 'Susz'),
('Warmińsko-mazurskie', 'Szczytno'),
('Warmińsko-mazurskie', 'Tolkmicko'),
('Warmińsko-mazurskie', 'Węgorzewo'),
('Warmińsko-mazurskie', 'Wielbark'),
('Warmińsko-mazurskie', 'Zalewo'),
('Wielkopolskie', 'Bojanowo'),
('Wielkopolskie', 'Borek Wielkopolski'),
('Wielkopolskie', 'Budzyń'),
('Wielkopolskie', 'Buk'),
('Wielkopolskie', 'Chocz'),
('Wielkopolskie', 'Chodzież'),
('Wielkopolskie', 'Czarnków'),
('Wielkopolskie', 'Czempiń'),
('Wielkopolskie', 'Czerniejewo'),
('Wielkopolskie', 'Dąbie'),
('Wielkopolskie', 'Dobra'),
('Wielkopolskie', 'Dobrzyca'),
('Wielkopolskie', 'Dolsk'),
('Wielkopolskie', 'Gniezno'),
('Wielkopolskie', 'Golina'),
('Wielkopolskie', 'Gołańcz'),
('Wielkopolskie', 'Gostyń'),
('Wielkopolskie', 'Grabów nad Prosną'),
('Wielkopolskie', 'Grodzisk Wielkopolski'),
('Wielkopolskie', 'Jaraczewo'),
('Wielkopolskie', 'Jarocin'),
('Wielkopolskie', 'Jastrowie'),
('Wielkopolskie', 'Jutrosin'),
('Wielkopolskie', 'Kaczory'),
('Wielkopolskie', 'Kalisz'),
('Wielkopolskie', 'Kępno'),
('Wielkopolskie', 'Kleczew'),
('Wielkopolskie', 'Kłecko'),
('Wielkopolskie', 'Kłodawa'),
('Wielkopolskie', 'Kobylin'),
('Wielkopolskie', 'Koło'),
('Wielkopolskie', 'Konin'),
('Wielkopolskie', 'Kostrzyn'),
('Wielkopolskie', 'Kościan'),
('Wielkopolskie', 'Koźmin Wielkopolski'),
('Wielkopolskie', 'Koźminek'),
('Wielkopolskie', 'Kórnik'),
('Wielkopolskie', 'Krajenka'),
('Wielkopolskie', 'Krobia'),
('Wielkopolskie', 'Krotoszyn'),
('Wielkopolskie', 'Krzywiń'),
('Wielkopolskie', 'Krzyż Wielkopolski'),
('Wielkopolskie', 'Książ Wielkopolski'),
('Wielkopolskie', 'Leszno'),
('Wielkopolskie', 'Luboń'),
('Wielkopolskie', 'Lwówek'),
('Wielkopolskie', 'Łobżenica'),
('Wielkopolskie', 'Margonin'),
('Wielkopolskie', 'Miasteczko Krajeńskie'),
('Wielkopolskie', 'Miejska Górka'),
('Wielkopolskie', 'Międzychód'),
('Wielkopolskie', 'Mikstat'),
('Wielkopolskie', 'Miłosław'),
('Wielkopolskie', 'Mosina'),
('Wielkopolskie', 'Murowana Goślina'),
('Wielkopolskie', 'Nekla'),
('Wielkopolskie', 'Nowe Skalmierzyce'),
('Wielkopolskie', 'Nowy Tomyśl'),
('Wielkopolskie', 'Oborniki'),
('Wielkopolskie', 'Obrzycko'),
('Wielkopolskie', 'Odolanów'),
('Wielkopolskie', 'Okonek'),
('Wielkopolskie', 'Opalenica'),
('Wielkopolskie', 'Opatówek'),
('Wielkopolskie', 'Osieczna'),
('Wielkopolskie', 'Ostroróg'),
('Wielkopolskie', 'Ostrów Wielkopolski'),
('Wielkopolskie', 'Ostrzeszów'),
('Wielkopolskie', 'Piła'),
('Wielkopolskie', 'Pleszew'),
('Wielkopolskie', 'Pniewy'),
('Wielkopolskie', 'Pobiedziska'),
('Wielkopolskie', 'Pogorzela'),
('Wielkopolskie', 'Poniec'),
('Wielkopolskie', 'Poznań'),
('Wielkopolskie', 'Przedecz'),
('Wielkopolskie', 'Puszczykowo'),
('Wielkopolskie', 'Pyzdry'),
('Wielkopolskie', 'Rakoniewice'),
('Wielkopolskie', 'Raszków'),
('Wielkopolskie', 'Rawicz'),
('Wielkopolskie', 'Rogoźno'),
('Wielkopolskie', 'Rychwał'),
('Wielkopolskie', 'Rydzyna'),
('Wielkopolskie', 'Sieraków'),
('Wielkopolskie', 'Skoki'),
('Wielkopolskie', 'Słupca'),
('Wielkopolskie', 'Sompolno'),
('Wielkopolskie', 'Stawiszyn'),
('Wielkopolskie', 'Stęszew'),
('Wielkopolskie', 'Sulmierzyce'),
('Wielkopolskie', 'Swarzędz'),
('Wielkopolskie', 'Szamocin'),
('Wielkopolskie', 'Szamotuły'),
('Wielkopolskie', 'Ślesin'),
('Wielkopolskie', 'Śmigiel'),
('Wielkopolskie', 'Śrem'),
('Wielkopolskie', 'Środa Wielkopolska'),
('Wielkopolskie', 'Trzcianka'),
('Wielkopolskie', 'Trzemeszno'),
('Wielkopolskie', 'Tuliszków'),
('Wielkopolskie', 'Turek'),
('Wielkopolskie', 'Ujście'),
('Wielkopolskie', 'Wągrowiec'),
('Wielkopolskie', 'Wieleń'),
('Wielkopolskie', 'Wielichowo'),
('Wielkopolskie', 'Witkowo'),
('Wielkopolskie', 'Wolsztyn'),
('Wielkopolskie', 'Wronki'),
('Wielkopolskie', 'Września'),
('Wielkopolskie', 'Wyrzysk'),
('Wielkopolskie', 'Wysoka'),
('Wielkopolskie', 'Zagórów'),
('Wielkopolskie', 'Zbąszyń'),
('Wielkopolskie', 'Zduny'),
('Wielkopolskie', 'Złotów'),
('Wielkopolskie', 'Żerków'),
('Zachodniopomorskie', 'Barlinek'),
('Zachodniopomorskie', 'Barwice'),
('Zachodniopomorskie', 'Białogard'),
('Zachodniopomorskie', 'Biały Bór'),
('Zachodniopomorskie', 'Bobolice'),
('Zachodniopomorskie', 'Borne Sulinowo'),
('Zachodniopomorskie', 'Cedynia'),
('Zachodniopomorskie', 'Chociwel'),
('Zachodniopomorskie', 'Chojna'),
('Zachodniopomorskie', 'Choszczno'),
('Zachodniopomorskie', 'Czaplinek'),
('Zachodniopomorskie', 'Człopa'),
('Zachodniopomorskie', 'Darłowo'),
('Zachodniopomorskie', 'Dębno'),
('Zachodniopomorskie', 'Dobra'),
('Zachodniopomorskie', 'Dobrzany'),
('Zachodniopomorskie', 'Drawno'),
('Zachodniopomorskie', 'Drawsko Pomorskie'),
('Zachodniopomorskie', 'Dziwnów'),
('Zachodniopomorskie', 'Golczewo'),
('Zachodniopomorskie', 'Goleniów'),
('Zachodniopomorskie', 'Gościno'),
('Zachodniopomorskie', 'Gryfice'),
('Zachodniopomorskie', 'Gryfino'),
('Zachodniopomorskie', 'Ińsko'),
('Zachodniopomorskie', 'Kalisz Pomorski'),
('Zachodniopomorskie', 'Kamień Pomorski'),
('Zachodniopomorskie', 'Karlino'),
('Zachodniopomorskie', 'Kołobrzeg'),
('Zachodniopomorskie', 'Koszalin'),
('Zachodniopomorskie', 'Lipiany'),
('Zachodniopomorskie', 'Łobez'),
('Zachodniopomorskie', 'Maszewo'),
('Zachodniopomorskie', 'Mielno'),
('Zachodniopomorskie', 'Mieszkowice'),
('Zachodniopomorskie', 'Międzyzdroje'),
('Zachodniopomorskie', 'Mirosławiec'),
('Zachodniopomorskie', 'Moryń'),
('Zachodniopomorskie', 'Myślibórz'),
('Zachodniopomorskie', 'Nowe Warpno'),
('Zachodniopomorskie', 'Nowogard'),
('Zachodniopomorskie', 'Pełczyce'),
('Zachodniopomorskie', 'Płoty'),
('Zachodniopomorskie', 'Polanów'),
('Zachodniopomorskie', 'Police'),
('Zachodniopomorskie', 'Połczyn-Zdrój'),
('Zachodniopomorskie', 'Pyrzyce'),
('Zachodniopomorskie', 'Recz'),
('Zachodniopomorskie', 'Resko'),
('Zachodniopomorskie', 'Sianów'),
('Zachodniopomorskie', 'Sławno'),
('Zachodniopomorskie', 'Stargard'),
('Zachodniopomorskie', 'Stepnica'),
('Zachodniopomorskie', 'Suchań'),
('Zachodniopomorskie', 'Szczecin'),
('Zachodniopomorskie', 'Szczecinek'),
('Zachodniopomorskie', 'Świdwin'),
('Zachodniopomorskie', 'Świnoujście'),
('Zachodniopomorskie', 'Trzcińsko-Zdrój'),
('Zachodniopomorskie', 'Trzebiatów'),
('Zachodniopomorskie', 'Tuczno'),
('Zachodniopomorskie', 'Tychowo'),
('Zachodniopomorskie', 'Wałcz'),
('Zachodniopomorskie', 'Węgorzyno'),
('Zachodniopomorskie', 'Wolin'),
('Zachodniopomorskie', 'Złocieniec');