POST http://localhost:7070/SDEmpApp/job-advertisement/create/2
Content-Type: application/json

{
  "localization": {
    "provinceName": "Mazowieckie",
    "cityName": "Warszawa"
  },
  "languages": "polish",
  "duties": "all duties",
  "formOfWork": "HYBRID",
  "skillsNeeded": "JAVA;SQL;PYTHON"
}
###

GET http://localhost:7070/SDEmpApp/job-advertisement/find/form-of-work
Content-Type: application/json

{
  "formOfWork": "IN_PLACE"
}
###

GET http://localhost:7070/SDEmpApp/job-advertisement/find/skills
Content-Type: application/json

{
  "skills": [
    {"skill": "JAVA"},
    {"skill": "PYTHON"},
    {"skill": "SQL"}
  ]
}
###

GET http://localhost:7070/SDEmpApp/job-advertisement/find/specified-skills
Content-Type: application/json

{
  "skills": [
    {"skill": "JAVA"},
    {"skill": "PYTHON"},
    {"skill": "SQL"}
  ]
}
