### create job seeker
POST http://localhost:7070/SDEmpApp/job-seeker/create
Content-Type: application/json

{
  "localization": {
    "provinceName": "Dolnośląskie",
    "cityName": "Bardo"
  },
  "name": "jannew3",
  "surname": "mikolajek3",
  "isStudent": true,
  "email": "emai3@gmail.com",
  "git": "https://github.com/username3",
  "phone": "+48 300 000 000",
  "linkedin": "https://www.linkedin.com/in/name3-surname3-123/",
  "cv": "cv",
  "languages": "FRENCH;GERMAN;ESTONIAN",
  "skills": "KOTLIN;GOLANG",
  "formsOfEmployment": "FREELANCE",
  "formsOfWork": "HYBRID",
  "experience": "1 > 2",
  "aboutMe": "aboutMe",
  "lookingForJob": true
}

### upadte job seeker
PUT http://localhost:7070/SDEmpApp/job-seeker/update-data/4
Content-Type: application/json

{
  "name": "new name",
  "surname": "new surname",
  "email": "email@gmail.com",
  "git": "https://github.com/username",
  "linkedin": "https://www.linkedin.com/in/name-surname-123/",
  "isStudent": true,
  "phone": "+48 123 123 123",
  "cv": "new cv",
  "languages": "new languages",
  "skills": "new skills",
  "formsOfEmployment": "B2B",
  "formsOfWork": "HYBRID",
  "experience": "0 >= 1",
  "aboutMe": "new aboutMe",
  "lookingForJob": false
}

###
GET http://localhost:7070/SDEmpApp/job-seeker/find/by-username/jan mikolajek new

### find job seeker
GET http://localhost:7070/SDEmpApp/job-seeker/find
Content-Type: application/json

{
  "localization": {
    "provinceName": "Mazowieckie",
    "cityName": "Warszawa"
  }
}
