POST http://localhost:7070/SDEmpApp/job-advertisement/create/1
Content-Type: application/json

{
  "localization": {
    "provinceName": "Dolnośląskie",
    "cityName": "Bardo"
  },
  "experienceNeeded": "5 > ",
  "salaryFrom": 8000,
  "salaryTo": 10000,
  "languages": "GREEK",
  "duties": "8",
  "formOfWork": "HYBRID",
  "seniority": "EXPERT",
  "skillsNeeded": ".NET"
}
###

PUT http://localhost:7070/SDEmpApp/job-advertisement/update/3
Content-Type: application/json

{
  "localization": {
    "provinceName": "Mazowieckie",
    "cityName": "Warszawa"
  },
  "languages": "GREEK",
  "duties": "all duties",
  "formOfWork": "HYBRID",
  "skillsNeeded": "JAVA"
}
###

GET http://localhost:7070/SDEmpApp/job-advertisement/find/form-of-work
Content-Type: application/json

{
  "formOfWork": "IN_PLACE"
}
###

GET http://localhost:7070/SDEmpApp/job-advertisement/find/skills
Content-Type: application/json

{
  "skills": [
    {"skill": "JAVA"},
    {"skill": "PYTHON"},
    {"skill": "SQL"}
  ]
}
###

GET http://localhost:7070/SDEmpApp/job-advertisement/find/specified-skills
Content-Type: application/json

{
  "skills": [
    {"skill": "JAVA"},
    {"skill": "SQL"}
  ]
}
###

GET http://localhost:7070/SDEmpApp/job-advertisement/find/languages
Content-Type: application/json

{
  "languageDTOs": [
    {"language": "POLISH"},
    {"language": "SLOVAK"},
    {"language": "NORWEGIAN"}
  ]
}
###

GET http://localhost:7070/SDEmpApp/job-advertisement/find/specified-languages
Content-Type: application/json

{
  "languageDTOs": [
    {"language": "GREEK"}
  ]
}
###

GET http://localhost:7070/SDEmpApp/job-advertisement/find/by-localization
Content-Type: application/json

{
"provinceName": "Dolnośląskie",
"cityName": "Bardo"
}
###

GET http://localhost:7070/SDEmpApp/job-advertisement/find/by-experience-needed
Content-Type: application/json

{
  "experience": "MIN_1"
}
###

GET http://localhost:7070/SDEmpApp/job-advertisement/find/by-salary
Content-Type: application/json

{
  "salary": 9000
}
###

GET http://localhost:7070/SDEmpApp/job-advertisement/find/by-seniority
Content-Type: application/json

{
  "seniorityDTOs": [
    {"seniority": "JUNIOR"},
    {"seniority": "TRAINEE"}
  ]

}
