POST http://localhost:7070/SDEmpApp/job-advertisement/create/1
Content-Type: application/json

{
  "localization": {
    "provinceName": "Dolnośląskie",
    "cityName": "Bardo"
  },
  "experienceNeeded": "0 >= 1",
  "salaryFrom": 8000,
  "salaryTo": 10000,
  "languages": "POLISH;SLOVAK;NORWEGIAN",
  "duties": "8",
  "formOfWork": "IN_PLACE",
  "seniority": "JUNIOR",
  "skillsNeeded": "JAVA;SQL"
}
###

PUT http://localhost:7070/SDEmpApp/job-advertisement/update/3
Content-Type: application/json

{
  "localization": {
    "provinceName": "Dolnośląskie",
    "cityName": "Bardo"
  },
  "languages": "GREEK",
  "duties": "all duties",
  "formOfWork": "HYBRID",
  "skillsNeeded": "JAVA"
}
###

GET http://localhost:7070/SDEmpApp/job-advertisement/find
Content-Type: application/json

{
  "localizationDTO": {
    "provinceName": "Mazowieckie",
    "cityName": "Warszawa"
  },
  "formOfWorkDTO": {
    "formOfWork": "IN_PLACE"
  },
  "experienceDTO": {
    "experience": "MIN_1"
  },
  "salary": {
    "salary": 9000
  }
}
