POST http://localhost:7070/SDEmpApp/job-seeker/create
Content-Type: application/json

{
  "name": "jannew10",
  "surname": "mikolajek10",
  "isStudent": true,
  "email": "emai10@gmail.com",
  "git": "https://github.com/username10",
  "phone": "+48 100 000 000",
  "linkedin": "https://www.linkedin.com/in/name10-surname10-123/",
  "cv": "cv",
  "languages": "languages",
  "skills": "skills",
  "b2bNormalFit": "B2B",
  "formOfWork": "HYBRID",
  "experience": "0",
  "aboutMe": "aboutMe",
  "lookingForJob": false
}

###

PUT http://localhost:7070/SDEmpApp/job-seeker/update-data/1
Content-Type: application/json

{
  "name": "new name1",
  "surname": "new surname1",
  "email": "email1@gmail.com",
  "git": "https://github.com/username1",
  "linkedin": "https://www.linkedin.com/in/name1-surname1-123/",
  "isStudent": true,
  "phone": "+48 123 123 123",
  "cv": "new cv",
  "languages": "new languages",
  "skills": "new skills",
  "b2bNormalFit": "B2B",
  "formOfWork": "HYBRID",
  "experience": "0 >= 1",
  "aboutMe": "new aboutMe",
  "lookingForJob": false
}

###

GET http://localhost:7070/SDEmpApp/job-seeker/find/by-username/jan mikolajek new
