### login user
POST http://localhost:7070/SDEmpApp/auth/login
Content-Type: application/json

{
  "email": "job_seeker@gmail.com",
  "password": "1234"
}

### login admin
POST http://localhost:7070/SDEmpApp/auth/login
Content-Type: application/json

{
  "email": "company@gmail.com",
  "password": "1234"
}

### register
POST http://localhost:7070/SDEmpApp/auth/register
Content-Type: application/json

{
  "role": "USER",
  "email": "company@gmail.com",
  "password": "1234"
}

### add role JOB_SEEKER
PUT http://localhost:7070/SDEmpApp/main-page/create-role-for/14
Content-Type: application/json

{
  "roleName": "JOB_SEEKER"
}

### add role COMPANY
PUT http://localhost:7070/SDEmpApp/main-page/create-role-for/14
Content-Type: application/json

{
  "roleName": "COMPANY"
}

### get
GET http://localhost:7070/SDEmpApp/main-page/get
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJjb21wYW55QGdtYWlsLmNvbSIsImlhdCI6MTcxMzcxMzk2MywiZXhwIjoxNzEzNzE1NDk5fQ.45GJE6xmcnjNCJvlX3_qERCsyNPwh8kYtccqAU4R5lkZj-z8hHNS022Q6564GUp1

### get for user
GET http://localhost:7070/SDEmpApp/main-page/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJjb21wYW55QGdtYWlsLmNvbSIsImlhdCI6MTcxMzcxMzk2MywiZXhwIjoxNzEzNzE1NDk5fQ.45GJE6xmcnjNCJvlX3_qERCsyNPwh8kYtccqAU4R5lkZj-z8hHNS022Q6564GUp1

### get for job seeker
GET http://localhost:7070/SDEmpApp/main-page/job_seeker
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJjb21wYW55QGdtYWlsLmNvbSIsImlhdCI6MTcxMzcxMzk2MywiZXhwIjoxNzEzNzE1NDk5fQ.45GJE6xmcnjNCJvlX3_qERCsyNPwh8kYtccqAU4R5lkZj-z8hHNS022Q6564GUp1

### get for company
GET http://localhost:7070/SDEmpApp/main-page/company
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJjb21wYW55QGdtYWlsLmNvbSIsImlhdCI6MTcxMzcxMzk2MywiZXhwIjoxNzEzNzE1NDk5fQ.45GJE6xmcnjNCJvlX3_qERCsyNPwh8kYtccqAU4R5lkZj-z8hHNS022Q6564GUp1
